//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPDO_INFO
    {
        public IPDO_INFO()
        {
            this.IPDO_gerTerm = new HashSet<IPDO_gerTerm>();
            this.IPDO_Submercado = new HashSet<IPDO_Submercado>();
        }
    
        public int id { get; set; }
        public System.DateTime dt_update { get; set; }
        public System.DateTime dt_ipdo { get; set; }
        public string ds_arquivo { get; set; }
        public Nullable<decimal> prod_itaipu { get; set; }
        public Nullable<decimal> prod_nuclear { get; set; }
        public Nullable<decimal> inter_se_fc { get; set; }
        public Nullable<decimal> inter_se_ne { get; set; }
        public Nullable<decimal> inter_s_se { get; set; }
        public Nullable<decimal> inter_n_fc { get; set; }
        public Nullable<decimal> inter_fc_ne { get; set; }
    
        public virtual ICollection<IPDO_gerTerm> IPDO_gerTerm { get; set; }
        public virtual ICollection<IPDO_Submercado> IPDO_Submercado { get; set; }
    }
}
