//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vazoes_Observadas
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public int Cod_Posto { get; set; }
        public string Nome_Posto { get; set; }
        public string Bacia { get; set; }
        public string Tipo_Vazao { get; set; }
        public Nullable<decimal> Vazao { get; set; }
        public System.DateTime Data_Update { get; set; }
    }
}
