//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA_VAZAO
    {
        public System.DateTime data { get; set; }
        public int posto { get; set; }
        public int qnat { get; set; }
        public int qinc { get; set; }
        public string fonte { get; set; }
    }
}
