//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class dePara_IPDO_DC
    {
        public string nomeIPDO { get; set; }
        public int idDadger { get; set; }
    }
}
