//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPDO_Submercado
    {
        public int id { get; set; }
        public int id_ipdo { get; set; }
        public int num_sub { get; set; }
        public Nullable<decimal> prod_hidro_veri { get; set; }
        public Nullable<decimal> prod_term_veri { get; set; }
        public Nullable<decimal> prod_term_prog { get; set; }
        public Nullable<decimal> prod_eolica_veri { get; set; }
        public Nullable<decimal> carga_veri { get; set; }
        public Nullable<decimal> reservatorio_max { get; set; }
        public Nullable<decimal> reservatorio_atual { get; set; }
        public Nullable<decimal> reservatorio_atual_porc { get; set; }
        public Nullable<decimal> ENA { get; set; }
        public Nullable<decimal> term_el { get; set; }
        public Nullable<decimal> term_en { get; set; }
        public Nullable<decimal> term_in { get; set; }
        public Nullable<decimal> term_ex { get; set; }
        public Nullable<decimal> term_te { get; set; }
        public Nullable<decimal> term_ge { get; set; }
        public Nullable<decimal> term_pe { get; set; }
        public Nullable<decimal> term_gfom { get; set; }
        public Nullable<decimal> term_gsub { get; set; }
        public Nullable<decimal> term_er { get; set; }
        public Nullable<decimal> term_null { get; set; }
        public Nullable<decimal> prod_solar_veri { get; set; }
        public Nullable<decimal> term_rro { get; set; }
    
        public virtual IPDO_INFO IPDO_INFO { get; set; }
    }
}
