//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPDO_gerTerm
    {
        public int id { get; set; }
        public int id_ipdo { get; set; }
        public string usina { get; set; }
        public int tipo { get; set; }
        public decimal valor_verif { get; set; }
        public Nullable<decimal> valor_prog { get; set; }
        public string submercado { get; set; }
    
        public virtual IPDO_gerTipo IPDO_gerTipo { get; set; }
        public virtual IPDO_INFO IPDO_INFO { get; set; }
    }
}
