//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postos
    {
        public int id { get; set; }
        public System.DateTime dt_entrada { get; set; }
        public string nome { get; set; }
        public string bacia { get; set; }
        public Nullable<int> submercado { get; set; }
        public Nullable<decimal> produtibilidade { get; set; }
        public string observacao { get; set; }
        public Nullable<int> chuvaVazao { get; set; }
        public Nullable<int> previvaz { get; set; }
        public Nullable<int> calculado { get; set; }
        public Nullable<int> especial { get; set; }
    }
}
