//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecipitacaoMdl
    {
        public System.DateTime Data { get; set; }
        public Nullable<System.DateTime> DataAtualizacao { get; set; }
        public string Bacia { get; set; }
        public string SubBacia { get; set; }
        public double Precipitacao1 { get; set; }
        public string Fonte { get; set; }
    }
}
