//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuvaVazaoTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDH
    {
        public System.DateTime Data { get; set; }
        public int Posto { get; set; }
        public int Vaz_nat { get; set; }
        public Nullable<int> Vaz_Inc { get; set; }
        public Nullable<decimal> Reserv { get; set; }
    }
}
